[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_vestiny = "98vJxJanGrYXsw22T8ERBweXvPWLEQwsxbpXAjiFdeKf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn jest"
